### ISSUE TITLE
Crash Report for Gas Centrifuge

### ISSUE THREAD

**Issue by c5001481cepheus** [Aurilisdev/Physica#120]
Upon placing the 'Gas Centrifuge' down in the world, a crash occurs.

On 1.16.5 Minecraft:

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/18/21 12:04 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: electrodynamics/prefab/tile/components/type/ComponentFluidHandler
	at nuclearscience.common.tile.TileGasCentrifuge.<init>(TileGasCentrifuge.java:38) ~[?:1.16.5-0.3.0-0] {re:classloading}
	at nuclearscience.common.block.BlockGasCentrifuge.createTileEntity(BlockGasCentrifuge.java:12) ~[?:1.16.5-0.3.0-0] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:120) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:289) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_241211_a_(World.java:199) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:149) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:187) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$13204/1135835364.run(Unknown Source) ~[?:?] {}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:167) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$11867/845301742.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2966920480 bytes (2829 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 6
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.8.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.8
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.8-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		openbackup-1.16.x-1.1.1.jar                       |OpenBackup                    |openbackup                    |1.16.x-1.1.1        |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.90.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.90           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |Manifest: NOSIGNATURE
		ToolSwap-1.16.2-1.3.2.jar                         |ToolSwap                      |toolswap                      |1.3.2               |DONE      |Manifest: NOSIGNATURE
		SimplyJetpacks2-1.16.5-2.6.11.2.jar               |Simply Jetpacks 2             |simplyjetpacks                |1.16.5-2.6.11.2     |DONE      |Manifest: NOSIGNATURE
		teleportmod_1.16.3-1.1.3.jar                      |Teleport++                    |teleportmod                   |1.1.3               |DONE      |Manifest: NOSIGNATURE
		inventoryprofiles-forge-1.16.2-0.4.2.jar          |Inventory Profiles            |inventoryprofiles             |0.4.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.129.jar                          |Just Enough Items             |jei                           |7.7.1.129           |DONE      |Manifest: NOSIGNATURE
		ChickenChunks-1.16.5-2.9.0.87-universal.jar       |ChickenChunks                 |chickenchunks                 |2.9.0.87            |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		flywheel-1.16-0.2.4.jar                           |Flywheel                      |flywheel                      |1.16-0.2.4          |DONE      |Manifest: NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2f.jar                       |Create                        |create                        |v0.3.2f             |DONE      |Manifest: NOSIGNATURE
		ftb-backups-2.1.2.2.jar                           |FTB Backups                   |ftbbackups                    |2.1.2.2             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |DONE      |Manifest: NOSIGNATURE
		[1.16.4][forge35.1.0]mod_PickupWidelySMP_v1.2.4.ja|Pickup Widely SMP             |pickupwidelysmp               |1.2.4               |DONE      |Manifest: NOSIGNATURE
		[1.16.5]+SecurityCraft+v1.8.23.jar                |SecurityCraft                 |securitycraft                 |v1.8.23             |DONE      |Manifest: NOSIGNATURE
		Nuclear+Science-1.16.5-0.3.0-0.jar                |Nuclear Science               |nuclearscience                |1.16.5-0.3.0-0      |DONE      |Manifest: NOSIGNATURE
		configured-1.3.0-1.16.5.jar                       |Configured                    |configured                    |1.3.0               |DONE      |Manifest: NOSIGNATURE
		structurize-0.13.252-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.252-ALPHA      |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		secretrooms-1.16.5-1.1.2.jar                      |Secret Rooms 6                |secretroomsmod                |1.16.5-1.1.2        |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.0.68-BETA-universal.jar            |MineColonies                  |minecolonies                  |1.0.68-BETA         |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.16-5.0.23.jar                          |McJtyLib                      |mcjtylib                      |1.16-5.0.23         |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.0.11.jar                       |RFToolsBase                   |rftoolsbase                   |1.16-2.0.11         |DONE      |Manifest: NOSIGNATURE
		rftoolscontrol-1.16-4.0.11.jar                    |RFToolsControl                |rftoolscontrol                |1.16-4.0.11         |DONE      |Manifest: NOSIGNATURE
		platos-1.5.1.jar                                  |Plato's Transporters          |platos                        |1.5.1               |DONE      |Manifest: NOSIGNATURE
		Electrodynamics-1.16.5-0.5.0-1.jar                |Electrodynamics               |electrodynamics               |1.16.5-0.5.0-1      |DONE      |Manifest: NOSIGNATURE
		PackingTape-1.16.5-0.10.1.jar                     |Packing Tape                  |packingtape                   |0.10.1              |DONE      |Manifest: NOSIGNATURE
		Ballistix+1.16.5-0.3.0-0.jar                      |Ballistix                     |ballistix                     |1.16.5-0.3.0-0      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.8-universal.jar                 |Forge                         |forge                         |36.2.8              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		cofh_core-1.16.5-1.3.1.jar                        |CoFH Core                     |cofh_core                     |1.3.1               |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.16.5-1.3.2.jar               |Thermal Series                |thermal                       |1.3.2               |DONE      |Manifest: NOSIGNATURE
		thermal_expansion-1.16.5-1.3.0.jar                |Thermal Expansion             |thermal_expansion             |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		MineMenu-1.16.4-1.8.7.jar                         |MineMenu                      |minemenu                      |1.16.4-1.8.7        |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.3.434-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.3.434           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		thutcore-1.16.4-8.2.0.jar                         |Thut Core                     |thutcore                      |8.2.0               |DONE      |Manifest: NOSIGNATURE
		thuttech-1.16.4-9.1.2.jar                         |Thut Elevators                |thuttech                      |9.1.2               |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.9.15.jar                         |Refined Storage               |refinedstorage                |1.9.15              |DONE      |Manifest: NOSIGNATURE
		SimpleDivingGear-5.0.5+mc+1.16.5.jar              |Simple Diving Gear            |simpledivegear                |5.0.5 mc 1.16.5     |DONE      |Manifest: NOSIGNATURE
		draw_bridge-1.16.5-1.6.1.26.jar                   |Draw Bridge                   |drawbridge                    |1.6.1.26            |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
	Crash Report UUID: cd1f3295-37d6-4461-8fb9-3ed144d029d0
	Player Count: 1 / 8; [ServerPlayerEntity['Asyrium'/43230, l='ServerLevel[Sacricilia]', x=7149.35, y=80.00, z=14000.74]]
	Data Packs: vanilla, mod:openbackup (incompatible), mod:usefulbackpacks, mod:theoneprobe, mod:toolswap (incompatible), mod:simplyjetpacks, mod:teleportmod, mod:inventoryprofiles (incompatible), mod:jei, mod:chickenchunks (incompatible), mod:flywheel, mod:create, mod:ftbbackups (incompatible), mod:journeymap (incompatible), mod:securitycraft (incompatible), mod:nuclearscience, mod:structurize, mod:worldedit (incompatible), mod:uteamcore, mod:minecolonies (incompatible), mod:electrodynamics, mod:packingtape (incompatible), mod:ballistix, mod:forge, mod:cofh_core (incompatible), mod:thermal (incompatible), mod:thermal_expansion (incompatible), mod:codechickenlib (incompatible), mod:thutcore, mod:thuttech, mod:simpledivegear (incompatible), mod:drawbridge, mod:mcjtylib, mod:rftoolsbase, mod:rftoolscontrol, mod:minemenu, mod:secretroomsmod (incompatible), mod:platos, mod:pickupwidelysmp (incompatible), mod:configured, mod:refinedstorage, mod:neat (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-v1.0.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 497.09
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
```

**Comment by aurilisdev** [comment]
Ur version of nuclear science is severely outdated for 1.16.5 so u just have to update. U might wanna look at my other mods to see if those are outdated as well but I can confirm that ur electrodynamics version is up to date

**Comment by c5001481cepheus** [comment]
Thanks for your quick reply! Yes, I accidentally updated Electrodynamics only and not Nuclear Science. It works great now. Thank you!
