### ISSUE TITLE
[1.18.1] funny ioob

### ISSUE THREAD

**Issue by Yoghurt4C** [Aurilisdev/Physica#121]
```java
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?] {}
        at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[server-1.18.1-20211210.034407-srg.jar%23131!:?] {re:classloading}
        at electrodynamics.prefab.tile.components.type.ComponentInventory.m_8020_(ComponentInventory.java:197) ~[Electrodynamics-1.18.1-0.5.4-0.jar%2368!:1.18.1-0.5.4-0] {re:classloading}
        at electrodynamics.prefab.tile.components.type.ComponentInventory.getUpgradeContents(ComponentInventory.java:467) ~[Electrodynamics-1.18.1-0.5.4-0.jar%2368!:1.18.1-0.5.4-0] {re:classloading}
        at electrodynamics.prefab.tile.components.type.ComponentProcessor.tickServer(ComponentProcessor.java:81) ~[Electrodynamics-1.18.1-0.5.4-0.jar%2368!:1.18.1-0.5.4-0] {re:classloading}
        at electrodynamics.prefab.tile.components.type.ComponentTickable.tickServer(ComponentTickable.java:61) ~[Electrodynamics-1.18.1-0.5.4-0.jar%2368!:1.18.1-0.5.4-0] {re:classloading}
        at electrodynamics.prefab.tile.components.type.ComponentTickable.performTick(ComponentTickable.java:82) ~[Electrodynamics-1.18.1-0.5.4-0.jar%2368!:1.18.1-0.5.4-0] {re:classloading}
        at electrodynamics.prefab.block.GenericEntityBlock.lambda$getTicker$0(GenericEntityBlock.java:47) ~[Electrodynamics-1.18.1-0.5.4-0.jar%2368!:1.18.1-0.5.4-0] {re:classloading}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.1-20211210.034407-srg.jar%23131!:?] {re:classloading}
        
-- Block entity being ticked --
Details:
        Name: electrodynamics:reinforcedalloyer // electrodynamics.common.tile.TileReinforcedAlloyer
        Block: Block{electrodynamics:reinforcedalloyer}[facing=west,waterlogged=false]

```

**Comment by aurilisdev** [comment]
When does this occur?

**Comment by Yoghurt4C** [comment]
when the tile is instantiated and loaded

**Comment by aurilisdev** [comment]
So not on placement?

**Comment by aurilisdev** [comment]
Nvm this is fixed in the newest dev version. Will be released at the beginning of next month :D
