### ISSUE TITLE
Double/Triple Wire Mill caused Server to crash, crashes every time the chunk is loaded

### ISSUE THREAD

**Issue by Kerbalino** [Aurilisdev/Physica#142]
Hello!

A couple of friends and me started a private modpack on a private server to play with, including Electrodynamics.

When he put iron ingots into a tripe wire mill he had, it instantly crashed the server. Every time the server loaded and somebody loads the chunk that the machine is residing in, it also crashes the server.

Below is the server's latest crashlog:

```
[19:15:39] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at electrodynamics.prefab.tile.components.type.ComponentProcessor.roomInItemBiSlots(ComponentProcessor.java:655) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at electrodynamics.prefab.tile.components.type.ComponentProcessor.canProcessItem2ItemRecipe(ComponentProcessor.java:221) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at electrodynamics.common.tile.TileWireMill.lambda$new$1(TileWireMill.java:63) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at electrodynamics.prefab.tile.components.type.ComponentProcessor.tickServer(ComponentProcessor.java:85) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at electrodynamics.prefab.tile.components.type.ComponentTickable.tickServer(ComponentTickable.java:61) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at electrodynamics.prefab.tile.components.type.ComponentTickable.performTick(ComponentTickable.java:82) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at electrodynamics.prefab.block.GenericEntityBlock.lambda$getTicker$0(GenericEntityBlock.java:47) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2357!:1.18.1-0.5.8-1]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23101!:?]
	... 5 more
```

**Comment by Kerbalino** [comment]
I've also managed to recreate the problem in singleplayer by using a Triple Wire Mill as well. The error log is as follows:

```
Time: 14/01/2022, 20:40
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at electrodynamics.prefab.tile.components.type.ComponentProcessor.roomInItemBiSlots(ComponentProcessor.java:655) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at electrodynamics.prefab.tile.components.type.ComponentProcessor.canProcessItem2ItemRecipe(ComponentProcessor.java:221) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at electrodynamics.common.tile.TileWireMill.lambda$new$1(TileWireMill.java:63) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at electrodynamics.prefab.tile.components.type.ComponentProcessor.tickServer(ComponentProcessor.java:85) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?] {re:mixin}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?] {re:mixin}
	at electrodynamics.prefab.tile.components.type.ComponentTickable.tickServer(ComponentTickable.java:61) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at electrodynamics.prefab.tile.components.type.ComponentTickable.performTick(ComponentTickable.java:82) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at electrodynamics.prefab.block.GenericEntityBlock.lambda$getTicker$0(GenericEntityBlock.java:47) ~[Electrodynamics-1.18.1-0.5.8-1.jar%2372!:1.18.1-0.5.8-1] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

```

**Comment by aurilisdev** [comment]
Has been fixed rn. Thanks for reporting this 👍🏻 :D
